[project]
name = "geometric_lib"
version = "0.1.0"
description = "A simple geometric library"
authors = [
    { name="Artem Batalov" }
]
readme = "README.md"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"